name = "ace-uncon-spectator"
author = "Foxymilyan"
prefix = "fox"
mainprefix = "f"

[hemtt.launch.default]
workshop = [
    "450814997", # CBA_A3
    "463939057"  # ACE3
]

parameters = [
    "-skipIntro",
    "-noSplash",
    "-showScriptErrors",
    "-debug",
    "-filePatching"
]

[version]
major = 0
minor = 1
patch = 0
build = 0